# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost # always use this to run database
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: video-store-consumer-api_development
test:
  <<: *default
  database: video-store-consumer-api_test

production:
  <<: *default
  database: video-store-consumer-api_production
  username: video-store-consumer-api
  password: <%= ENV['video-store-consumer-api_DATABASE_PASSWORD'] %>

